---
- name: "Testing the secrets"
  hosts: localhost
  connection: local

  tasks:
  - name: "set a var"
    shell: hostname
    register: varz
    #no_log: true

  - name: "Show"
    debug:
      var: varz

  - name: "set"
    set_fact:
      god6: "{{varz.stdout}}"
    #no_log: true

  - name: Debug
    debug:
      var: god6
