---
- name: "Testing the secrets"
  hosts: localhost
  connection: local

  tasks:
  - name: "set a var"
    shell: hostname
    register: varz
    no_log: true

  - name: "Show"
    debug:
      var: varz

  - name: "set"
    set_fact:
      comp_name: "{{varz.stdout}}"
    no_log: true

  - name: Debug
    debug:
      var: comp_name

  # - name: Set Stat
  #   set_stats:
  #     data:
  #       password: "{{comp_name}}"
  #   no_log: true
...